[package]
name = "lockc-common"
version = "0.1.0"
edition = "2021"

[features]
default = []
user = [ "aya", "thiserror" ]

[dependencies]
aya = { version = "0.11", optional = true }
thiserror = { version = "1.0", optional = true }

[lib]
path = "src/lib.rs"