[package]
name = "lockctl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aya = "0.11"
clap = "4.1"
cli-table = "0.4"
lockc-common = { path = "../lockc-common", features = ["cli", "user"] }
procfs = "0.15"
